version: '3.8'

services:
  nginx:
    # 镜像名 如果需要指定版本 就把 latest 换成版本号
    image: nginx
    # 容器名
    container_name: nginx-docker
    # 重启策略
    restart: always
    # 端口映射
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 证书映射
      - ./cert:/etc/nginx/cert
      # 配置文件映射
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - ./html:/usr/share/nginx/html
      # 日志目录
      - ./logs:/var/log/nginx
      # 主机本机时间文件映射 与本机时间同步
      - /etc/localtime:/etc/localtime:ro