version: "3"
services:
  redis:
    image: redis:5.0.8
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf:ro
      - ./data:/data/:rw
    restart: always
    command: redis-server /etc/redis/redis.conf
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - default